# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('text', models.TextField(verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('is_activ', models.BooleanField(default=False, verbose_name='\u041c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u044f')),
                ('metakeywords', models.CharField(blank=True, max_length=200, verbose_name='meta-keywords')),
                ('metadescription', models.CharField(blank=True, max_length=200, verbose_name='meta-description')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d')),
            ],
            options={
                'ordering': ['-create'],
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441/\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b/\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
    ]
