# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='metadescription',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='metakeywords',
        ),
    ]
