# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20171116_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
    ]
