# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='description',
        ),
    ]
