# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_desc_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc_category',
            field=models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
