# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_desc_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc_category',
        ),
    ]
