# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
