# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc_catalog',
            field=models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
