# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u0440\u0438\u044f', 'verbose_name_plural': '\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430'},
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
    ]
