# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170811_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False, verbose_name='\u041d\u043e\u0432\u044b\u0439 \u0442\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='product',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='vip \u0442\u043e\u0432\u0430\u0440'),
        ),
    ]
