# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_massa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='massa',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u041c\u0430\u0441\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='product',
            name='netto',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u0413\u0430\u0431\u0430\u0440\u0438\u0442\u044b'),
        ),
    ]
