# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_category_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('images', models.ImageField(blank=True, upload_to='products/%y/%m/%d/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e \u0430\u043b\u044c\u0431\u043e\u043c',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
    ]
