# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_albom'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
