# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170817_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='images',
            field=models.ImageField(blank=True, upload_to='products/thumbnail/%y/%m/%d/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
