# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20170818_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urlyoutube',
            field=models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
