# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_urlyoutube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
    ]
