# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20170822_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
    ]
