# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20170825_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter_default',
            field=models.IntegerField(default=30, verbose_name='\xd8 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_max',
            field=models.IntegerField(default=0, verbose_name='\xd8 \u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter_min',
            field=models.IntegerField(default=0, verbose_name='\xd8 \u043c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439'),
        ),
    ]
