# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20170906_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_two',
            field=models.TextField(blank=True, verbose_name='\u0414\u043e\u043f.\u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f'),
        ),
    ]
