# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_description_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='akciya',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0446\u0438\u044f'),
        ),
    ]
