# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timer_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0442\u0430\u0439\u043c\u0435\u0440\u0430'),
        ),
    ]
