# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-20 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_timer_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pod_zakaz',
            field=models.BooleanField(default=False, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u043f\u043e\u0434 \u0437\u0430\u043a\u0430\u0437'),
        ),
    ]
