# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('links', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0440\u043e\u043b\u0438\u043a')),
                ('v_timer', models.BooleanField(default=False, verbose_name='\u0422\u0430\u0439\u043c\u0435\u0440')),
                ('is_activ', models.BooleanField(default=False, verbose_name='\u041c\u043e\u0434\u0435\u0440\u0430\u0446\u0438\u044f')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d')),
            ],
            options={
                'ordering': ['create'],
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e \u0441\u043b\u0430\u0439\u0434\u0435\u0440',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u044b',
            },
        ),
    ]
