# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidos', '0002_video_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_slider',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
