# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidos', '0004_video_slider_link_tovar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_slider',
            name='link_tovar',
            field=models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0442\u043e\u0432\u0430\u0440'),
        ),
    ]
