# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidos', '0005_auto_20171124_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_slider',
            name='timer_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0442\u0430\u0439\u043c\u0435\u0440\u0430'),
        ),
    ]
