# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
    ]
