# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='myname',
            field=models.CharField(default='', max_length=150, verbose_name='\u0424\u0418\u041e'),
            preserve_default=False,
        ),
    ]
