# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20170923_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_tems',
            field=models.CharField(blank=True, max_length=150, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0442\u0435\u043c\u044b'),
        ),
    ]
