# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180323_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=150, verbose_name='\u0424\u0418\u041e')),
                ('post_email', models.EmailField(blank=True, max_length=100, verbose_name='e-mail')),
                ('post_phone', models.CharField(max_length=100, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('post_adres', models.CharField(max_length=150, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('post_delivery', models.CharField(choices=[('post_russia', '\u041f\u043e\u0447\u0442\u0430 \u0420\u043e\u0441\u0441\u0438\u0438'), ('post_cdek', '\u0421\u043b\u0443\u0436\u0431\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438 \u0421\u0414\u042d\u041a'), ('post_dpd', '\u0421\u043b\u0443\u0436\u0431\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438 DPD'), ('post_kit', '\u0421\u043b\u0443\u0436\u0431\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438 KIT')], max_length=150, verbose_name='\u0421\u043b\u0443\u0436\u0431\u0430 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
                ('payment_method', models.CharField(choices=[('nal', '\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u043c\u0438 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438'), ('bank', '\u041e\u043f\u043b\u0430\u0442\u0430 \u043a\u0430\u0440\u0442\u043e\u0439 \u0431\u0430\u043d\u043a\u0430'), ('walletone', '\u041e\u043d\u043b\u0430\u0439\u043d \u043e\u043f\u043b\u0430\u0442\u0430(walletone)')], max_length=100, verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('post_comments', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('post_created', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('post_update', models.DateTimeField(auto_now=True, verbose_name='\u0418\u0437\u043c\u0435\u043d\u0435\u043d')),
            ],
            options={
                'ordering': ('-post_created',),
                'verbose_name': '\u0411\u044b\u0441\u0442\u0440\u044b\u0439 \u0437\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0411\u044b\u0441\u0442\u0440\u044b\u0435 \u0437\u0430\u043a\u0430\u0437\u044b',
            },
        ),
    ]
