# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180416_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostOrder',
        ),
    ]
